theme: jekyll-theme-cayman
# title: JRP's Homepage
title: Ruipeng Jia (贾瑞鹏)
description: PhD student at Institute of Information Engineering, Chinese Academy of Sciences, studying computer science, focusing on machine learning for natural language.
